command_timeout = 700

[directory]
truncate_to_repo = false
truncation_length = 1

[git_branch]
format = "[$symbol$branch]($style) "

[golang]
disabled = true

[gcloud]
disabled = true

[git_state]
disabled = true

[git_commit]
disabled = true
